### ISSUE TITLE
Hangs after a few days

### ISSUE THREAD

**Issue by fourofspades** [H2CK/twonkyserver#2]
Webservice is running, but no content, and CPU is pegged at 50%, server is not accessible over DLNA.

I have seen this in docker and non-docker, ARM and AMD64 builds of 8.5.1 and it's driving me nuts.   Anyone know of a fix?  Twonky (Lynx Technology are only interested in selling licences, never response to support requests).

**Comment by H2CK** [comment]
I have seen this problem in the past also several times. But this must be fixed in the wonky server software. It can not be fixed in this docker image.
I tried to overcome this problem by restarting the docker image in the night.

**Comment by t09** [comment]
Maybe 8.5.2 fixes is

**Comment by H2CK** [comment]
I recently updated the docker image to Twonky Server 8.5.2 and ffmpg 4.3.2. The image should be available on docker hub soon. 
Please try if the problems disappears. But in the release notes of this version (8.5.2) I was not able to find a hint that this issue might be fixed.
