### ISSUE TITLE
Every Start - no Media Share until - webconfig - Twonky Account Login

### ISSUE THREAD

**Issue by Mofarocker33** [H2CK/twonkyserver#3]
Hi,

everytime the Server starts, it does not share Media. I first have to open the Webconfig Tab and insert my Twonky Username an Password.
Is this a RW Problem for the Config File on my Unraid Docker System?
Or may i have to insert those Information in the config or a seperate File?

Thanks in advance.
Mofa

![2024-06-01 11_43_26-Twonky Server](https://github.com/H2CK/twonkyserver/assets/148162944/5ea5caf0-0fa4-4c56-b767-d96bac644183)
![2024-06-01 11_43_37-Twonky Server](https://github.com/H2CK/twonkyserver/assets/148162944/296e7ff0-e23e-4709-b528-fa8df7716935)
![2024-06-01 11_43_59-Twonky Server](https://github.com/H2CK/twonkyserver/assets/148162944/e1be175e-15d1-4aea-9317-740db3035610)

**Comment by H2CK** [comment]
In newer versions the license information is stored in the file /usr/local/twonky/twonky.license

If you mount this file to a persistent storage outside of the container you should be able to redeploy the container without entering the license information again.

E.g.  
```
docker run -d --net=host --name=twonkyserver -v /path/to/twonky.license:/usr/local/twonky/twonky.license:rw -v /path/to/config:/config:rw -v /path/to/data:/data:ro -v /etc/localtime:/etc/localtime:ro dtjs48jkt/twonkyserver
```

**Comment by Mofarocker33** [comment]
For Unraid Users, this may Help
![2024-06-01 17_49_21-Mofa-NAS_UpdateContainer](https://github.com/H2CK/twonkyserver/assets/148162944/de796a07-5b26-41d0-bfc8-d5547607855f)
